version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: ${MSSQL_PID}
      MSSQL_TELEMETRY_ENABLED: ${MSSQL_TELEMETRY_ENABLED}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - uploads:/usr/src/app/uploads
    ports:
      - "1433:1433"

  app:
    build: .
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_HOST: mssql
    volumes:
      - uploads:/usr/src/app/uploads
    ports:
      - "8080:8080"
    depends_on:
      - mssql

volumes:
  uploads:
