version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: ${MSSQL_PID}
      MSSQL_TELEMETRY_ENABLED: ${MSSQL_TELEMETRY_ENABLED}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - uploads:/usr/src/app/uploads
    ports:
      - "1433:1433"

  app:
    build: .
    environment:
      PORT: ${PORT}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_HOST: mssql
    volumes:
      - uploads:/usr/src/app/uploads
    ports:
      - ${PORT}
    depends_on:
      - mssql

volumes:
  uploads:
