const tables = {
  Calendario: ["*"],
  Auxiliar: ["*"],
  Cliente: ["*"],
  CategoriaFasar: [
    "CategoriaFasarId",
    "Nombre",
    "Descripcion",
    //    "LibroFasar",
    "Predeterminado",
  ],
  Concepto: ["*"],
  ConfiguracionEquipo: ["*"],
  ConfiguracionMoneda: ["*"],
  Concursante: ["*"],
  ConfiguracionCalculoIndirectos: ["*"],
  ConfiguracionFactorEquipoCH: ["*"],
  CostoHorario: ["*"],
  DataBaseConfig: ["*"],
  Equipo: ["*"],
  FactorEquipoCH: ["*"],
  FamiliaDeIndices: ["*"],
  Familia: ["*"],
  Herramienta: ["*"],
  FinanciamientoAnticipos: ["*"],
  HojaDePresupuesto: ["*"],
  Material: ["*"],
  MonedaPropuesta: ["*"],
  Indirecto: ["*"],
  ManoDeObra: ["*"],
  Recurso: ["*"],
  MatrizDeRecursos: ["*"],
  ReferenciaDeIndices: ["*"],
  NaturalezaDeRecurso: ["*"],
  RenglonDeToc: ["*"],
  ProyectoPropuesta: [
    "ProyectoPropuestaId",
    "Nombre",
    "Autor",
    "Descripcion",
    "FechaCreacion",
    "ProtectionString",
    "ProjectTypeId",
    "PresupuestoCerrado",
    "ConfiguracionEquipoId",
    "ConfiguracionMonedaId",
    "ConfiguracionCalculoIndirectosId",
    "ConcursanteId",
    "ClienteId",
    "TablaDeConceptosId",
    "HojaDePresupuestoId",
    "Calle",
    "Ciudad",
    "CodigoPostal",
    "Pais",
    "CalculosNombreImpuesto",
    "CalculosPorcentajeImpuesto",
    "CalculosDecimalesEnCostos",
    "CalculosDecimalesEnFactoresEquipoCH",
    "CalculosDecimalesEnCantidadesMatrices",
    "CalculosDecimalesEnPorcentajes",
    "CalculosDecimalesEnCantidadesPresupuesto",
    "CalculosDecimalesEnOtrasCantidades",
    "CalculosDecimalesEnFactoresSobrecostos",
    "CalculosAjustesAplicarAjustepp2423",
    "CalculosAjustesAplicarAjustepp4439",
    "CalculosAjustesAplicarAjustepp5147",
    "CalculosAjustesAplicarAjustepp5167",
    "CalculosConsolidarCambiosEnPresupuesto",
    "ExplosionTipoAjuste",
    "ExplosionExplotarCostosHorarios",
    "VistaCompleta",
    "MostrarTitulos",
    "ElementoPorHoja",
    "IncluirDesglose",
    "FilaEnBlanco",
    "MostrarDistribucion",
    "OrigenPorcentajesIndirectos",
    "ISR",
    "PTU",
    "UtilidadPropuesta",
    "PeriodoPrimeraEstimacion",
    "Anticipos",
    "ImporteAnterior",
    "ImporteAnteriorMateriales",
    "SincronizarFechasFinanciamiento",
    "FechaInicioFinanciamiento",
    "FechaFinFinanciamiento",
    "UtilizaMateriales",
    "MaterialesExplosion",
    "FormatoCA",
    "FormatoFinancMat",
    "FormatoFinanciamiento",
    "FormatoUtilidad",
    "FormatoSobrecostos",
    "FormatoSobrecostosMat",
    "TipoCalculo",
    "PorcentajeSFP",
    "ConcursoConvocatoria",
    "ConcursoDescripcion",
    "ConcursoFechaDeConcurso",
    "ConcursoFechaDePublicacion",
    "ConcursoFechaDePresentacion",
    "ConcursoNumero",
    "ConcursoTipo",
    "ConcursoCalle",
    "ConcursoCiudad",
    "ConcursoCodigoPostal",
    "ConcursoPais",
    "ConcursoLeyDeConstruccion",
    "ManoObraAnio",
    "ManoObraFactorDeEmpresa",
    "ManoObraImpuestoNomina",
    "ManoObraJornadaDeTrabajo",
    "ManoObraRiesgoDeTrabajo",
    "ManoObraSalarioMinimoDF",
    "ManoObraTurnoDeTrabajo",
    "ManoObraHojaFSR",
    "PorcentajeSobreNomina",
    "FechaInicioProyecto",
    "FechaFinProyecto",
    "FechaInicioProgramaDeObra",
    "FechaFinProgramaDeObra",
    "MostrarFechasProyectoEnGantt",
    "MostrarFechasProgramaDeObraEnGantt",
    "InicioDeSemana",
    "SincronizarFechasProyectoConProgramaDeObra",
    "ObraControl",
    "ConnStringControl",
    "InfoAdic",
    "Version",
    "Estado",
    //    "DocFinanciamientoHorizontal",
    //    "DocFinanciamientoVertical",
    //    "DocUtilidad",
    //    "DocFSRIndirectos",
    //    "DocCad",
    //    "DocCargosAdicionales",
    //    "DocPie",
    "TipoEscalatoria",
    "ClaveAllPlan",
    "RoundType",
    "CampoPersonalizado1",
    "CampoPersonalizado2",
    "CampoPersonalizado3",
    "CampoPersonalizado4",
    "CampoPersonalizado5",
    "IndicadorEconomicoMN",
    "TasaIndicadorEconomicoMN",
    "PuntosaPagar",
    "PuntosaFavor",
    "Numero",
    "FechaDeFirma",
    "Ejercicio",
    "SincronizarFechas",
    "FechaDeInicio",
    "FechaDeTermino",
    "FechaDeInicioRecalendarizada",
    "FechaDeTerminoRecalendarizada",
    "PartidaPresupuestal",
    "SincronizarImporte",
    "Importe",
    "PorcentajeAnticipo",
    "PorcentajeFondoGarantia",
    "NombreDatoAdicional1",
    "ValorDatoAdicional1",
    "NombreDatoAdicional2",
    "ValorDatoAdicional2",
    "NombreDatoAdicional3",
    "ValorDatoAdicional3",
    "FirmaNombre1",
    "FirmaPuesto1",
    "FirmaTarea1",
    "FirmaNombre2",
    "FirmaPuesto2",
    "FirmaTarea2",
    "FirmaNombre3",
    "FirmaPuesto3",
    "FirmaTarea3",
    "FirmaNombre4",
    "FirmaPuesto4",
    "FirmaTarea4",
    "FirmaNombre5",
    "FirmaPuesto5",
    "FirmaTarea5",
    "FirmaNombre6",
    "FirmaPuesto6",
    "FirmaTarea6",
    "DeduccionAdicionalNombre1",
    "DeduccionAdicionalNombre2",
    "DeduccionAdicionalNombre3",
    "DeduccionAdicionalPorcentaje1",
    "DeduccionAdicionalPorcentaje2",
    "DeduccionAdicionalPorcentaje3",
    "ConvenioNumero",
    "ConvenioImporte",
    "ConvenioFechaDeInicio",
    "ConvenioFechaDeTermino",
    "IndirectoOficina",
    "IndirectoCampo",
    "Indirectos",
    "Financiamiento",
    "Utilidad",
    "CargosAdicionales",
    "OtrosPorcentajes",
    "Consolidado",
    "AplicarIndirectoOficina",
    "AplicarIndirectoCampo",
    "AplicarIndirctosConsolidado",
    "AplicarFinanciamiento",
    "AplicarUtilidad",
    "AplicarCargosAdicionales",
    "TipoCorrimientoFechas",
    "ActualizacionNecesaria",
    "BaseDeCalculoMO",
    "TipoCalculoRendimiento",
  ],
  RecursoComponente: ["*"],
  Sobrecosto: ["*"],
  TablaConceptos: ["*"],
  RenglonDePresupuesto: ["*"],
  UnidadDeTrabajo: ["*"],
};

export default tables;
